# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        TodoBundle\Entity\User:
            algorithm: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: TodoBundle:User
                property: userMail

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        #dev:
            #pattern: ^/(_(profiler|wdt)|css|images|js)/
            #pattern: ^/
            #security: false

        main:
            anonymous: ~
            form_login:
                login_path: todo_login
                check_path: todo_login
            provider: our_db_provider
            logout:
                path:   /logout
                target: /
            #pattern:    ^/
            #http_basic: ~

        #secured_area:


    #access_control:
        # require ROLE_ADMIN for /admin*
        #- { path: ^/admin, roles: ROLE_ADMIN }
