TodoBundle\Entity\User:
    type: entity
    table: user
    uniqueConstraints:
        iu__user__user_mail:
            columns:
                - user_mail
    id:
        userId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: user_id
            generator:
                strategy: IDENTITY
    fields:
        userName:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: user_name
        userPassword:
            type: string
            nullable: false
            length: 60
            options:
                fixed: true
            column: user_password
        userMail:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: user_mail
        userActive:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: user_active
        created:
            type: datetime
            nullable: false
            options:
                default: '1999-12-31 20:00:00'
        modified:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }
