todo_homepage:
    path: /
    defaults: { _controller: TodoBundle:Default:index }

todo_admin:
    path: /admin/
    defaults: { _controller: TodoBundle:Default:admin }

todo_signin:
    path: /signin/
    defaults: { _controller: TodoBundle:Sign:in }

todo_login:
    path: /login/
    defaults: { _controller: TodoBundle:Security:login }

todo_logout:
    path: /logout
