todo_homepage:
    path: /
    defaults: { _controller: TodoBundle:Default:index }

todo_admin:
    path: /admin/
    defaults: { _controller: TodoBundle:Default:admin }

todo_login:
    path: /login/
    defaults: { _controller: TodoBundle:Sign:login }

todo_logout:
    path: /logout

todo_signup:
    path: /signup
    defaults: { _controller: TodoBundle:Sign:signup }
